# Generated by Django 2.2.4 on 2019-08-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_auto_20190827_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='user_id',
        ),
    ]
